interface RoastDisplayProps {
  roast: string;
  username?: string;
  generatedAt?: string;
  temperature?: number;
  model?: string;
}

export function RoastDisplay({ roast, username, generatedAt, temperature = 0.7, model = 'gemini-pro' }: RoastDisplayProps) {
  return (
    <div className="bg-gradient-to-r from-orange-50 via-red-50 to-pink-50 dark:from-gray-800 dark:via-gray-900 dark:to-gray-950 border-2 border-orange-200 dark:border-gray-700 rounded-2xl shadow-2xl p-8">
      <div className="flex flex-col md:flex-row md:items-center justify-between mb-8 gap-4">
        <div>
          <div className="flex items-center gap-3 mb-2">
            <span className="text-3xl"></span>
            <h3 className="text-2xl font-bold text-gray-900 dark:text-white">
              Roast of @{username || 'User'}
            </h3>
          </div>
          <p className="text-gray-600 dark:text-gray-300">
            Generated by {model} • {generatedAt ? new Date(generatedAt).toLocaleDateString() : 'Just now'}
          </p>
        </div>
        <div className="flex gap-2">
          <span className="px-4 py-2 bg-red-100 dark:bg-red-900 text-red-800 dark:text-red-200 font-bold rounded-full">
            AI-Powered 
          </span>
          <span className="px-4 py-2 bg-blue-100 dark:bg-blue-900 text-blue-800 dark:text-blue-200 font-bold rounded-full">
            Temperature: {temperature}
          </span>
        </div>
      </div>
      
      <div className="prose prose-lg dark:prose-invert max-w-none mb-8">
        <div className="bg-white dark:bg-gray-800 rounded-xl p-8 shadow-inner">
          <p className="text-gray-800 dark:text-gray-200 whitespace-pre-line leading-relaxed text-lg">
            {roast}
          </p>
        </div>
      </div>
    </div>
  );
}